<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129000053 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE choice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, question_id INT NOT NULL, target_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1AB5A921E27F6BF ON choice (question_id)');
        $this->addSql('CREATE INDEX IDX_C1AB5A92991DB9B5 ON choice (target_question_id)');
        $this->addSql('CREATE TABLE participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_completed BOOLEAN NOT NULL, current_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB55E24FA0F35D66 ON participation (current_question_id)');
        $this->addSql('CREATE TABLE participation_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participation_id INT NOT NULL, choice_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0B8CC006ACE3B73 ON participation_answer (participation_id)');
        $this->addSql('CREATE INDEX IDX_A0B8CC00998666D1 ON participation_answer (choice_id)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, media_filename VARCHAR(255) DEFAULT NULL, media_type VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE questionnaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, start_question_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A64DAF4450E60B ON questionnaire (start_question_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A921E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A92991DB9B5 FOREIGN KEY (target_question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA0F35D66 FOREIGN KEY (current_question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE participation_answer ADD CONSTRAINT FK_A0B8CC006ACE3B73 FOREIGN KEY (participation_id) REFERENCES participation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation_answer ADD CONSTRAINT FK_A0B8CC00998666D1 FOREIGN KEY (choice_id) REFERENCES choice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questionnaire ADD CONSTRAINT FK_7A64DAF4450E60B FOREIGN KEY (start_question_id) REFERENCES question (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT FK_C1AB5A921E27F6BF');
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT FK_C1AB5A92991DB9B5');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24FA0F35D66');
        $this->addSql('ALTER TABLE participation_answer DROP CONSTRAINT FK_A0B8CC006ACE3B73');
        $this->addSql('ALTER TABLE participation_answer DROP CONSTRAINT FK_A0B8CC00998666D1');
        $this->addSql('ALTER TABLE questionnaire DROP CONSTRAINT FK_7A64DAF4450E60B');
        $this->addSql('DROP TABLE choice');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE participation_answer');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE questionnaire');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
