<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251130015904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT fk_c1ab5a92991db9b5');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT FK_C1AB5A92991DB9B5 FOREIGN KEY (target_question_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT fk_ab55e24fa0f35d66');
        $this->addSql('ALTER TABLE participation ADD respondent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA0F35D66 FOREIGN KEY (current_question_id) REFERENCES question (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FCE80CD19 FOREIGN KEY (respondent_id) REFERENCES "user" (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB55E24F5F37A13B ON participation (token)');
        $this->addSql('CREATE INDEX IDX_AB55E24FCE80CD19 ON participation (respondent_id)');
        $this->addSql('ALTER TABLE participation_answer DROP CONSTRAINT fk_a0b8cc00998666d1');
        $this->addSql('ALTER TABLE participation_answer ADD question_id INT NOT NULL');
        $this->addSql('ALTER TABLE participation_answer ALTER choice_id DROP NOT NULL');
        $this->addSql('ALTER TABLE participation_answer ADD CONSTRAINT FK_A0B8CC00998666D1 FOREIGN KEY (choice_id) REFERENCES choice (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation_answer ADD CONSTRAINT FK_A0B8CC001E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A0B8CC001E27F6BF ON participation_answer (question_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_participation_question ON participation_answer (participation_id, question_id)');
        $this->addSql('ALTER TABLE questionnaire ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE questionnaire ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE choice DROP CONSTRAINT FK_C1AB5A92991DB9B5');
        $this->addSql('ALTER TABLE choice ADD CONSTRAINT fk_c1ab5a92991db9b5 FOREIGN KEY (target_question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24FA0F35D66');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24FCE80CD19');
        $this->addSql('DROP INDEX UNIQ_AB55E24F5F37A13B');
        $this->addSql('DROP INDEX IDX_AB55E24FCE80CD19');
        $this->addSql('ALTER TABLE participation DROP respondent_id');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT fk_ab55e24fa0f35d66 FOREIGN KEY (current_question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE participation_answer DROP CONSTRAINT FK_A0B8CC00998666D1');
        $this->addSql('ALTER TABLE participation_answer DROP CONSTRAINT FK_A0B8CC001E27F6BF');
        $this->addSql('DROP INDEX IDX_A0B8CC001E27F6BF');
        $this->addSql('DROP INDEX unique_participation_question');
        $this->addSql('ALTER TABLE participation_answer DROP question_id');
        $this->addSql('ALTER TABLE participation_answer ALTER choice_id SET NOT NULL');
        $this->addSql('ALTER TABLE participation_answer ADD CONSTRAINT fk_a0b8cc00998666d1 FOREIGN KEY (choice_id) REFERENCES choice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE questionnaire DROP description');
        $this->addSql('ALTER TABLE questionnaire DROP created_at');
    }
}
